spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/<database_name>
    username: <user>
    password: <password>
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 4baef3ef37a61116ccb2f03fb1f6891355451c7220070b61d671268e2a82eb1b
      expiration: 8640000  #a day
      refresh-token:
        expiration: 604800000  # 7 days